// GENERATED by scripts/gen-routes.mjs — do not edit by hand.
/* eslint-disable */
import type { RouteModule } from "./http-router";

import * as route0 from "../app/api/agent/[id]/bash-output/route";
import * as route1 from "../app/api/agent/[id]/events/route";
import * as route2 from "../app/api/agent/[id]/lease/route";
import * as route3 from "../app/api/agent/[id]/route";
import * as route4 from "../app/api/agent/new/route";
import * as route5 from "../app/api/agent/running/route";
import * as route6 from "../app/api/app-update/route";
import * as route7 from "../app/api/auth/api-key/[provider]/route";
import * as route8 from "../app/api/auth/login/[provider]/route";
import * as route9 from "../app/api/auth/logout/[provider]/route";
import * as route10 from "../app/api/auth/providers/route";
import * as route11 from "../app/api/cwd/browse/route";
import * as route12 from "../app/api/cwd/validate/route";
import * as route13 from "../app/api/default-cwd/route";
import * as route14 from "../app/api/file-index/route";
import * as route15 from "../app/api/files/[...path]/route";
import * as route16 from "../app/api/git/diff/route";
import * as route17 from "../app/api/git/status/route";
import * as route18 from "../app/api/home/route";
import * as route19 from "../app/api/models-config/catalog/route";
import * as route20 from "../app/api/models-config/discover/route";
import * as route21 from "../app/api/models-config/route";
import * as route22 from "../app/api/models-config/test/route";
import * as route23 from "../app/api/models/route";
import * as route24 from "../app/api/plugins/check/route";
import * as route25 from "../app/api/plugins/route";
import * as route26 from "../app/api/project-trust/route";
import * as route27 from "../app/api/provider-usage/query/route";
import * as route28 from "../app/api/push/config/route";
import * as route29 from "../app/api/push/subscribe/route";
import * as route30 from "../app/api/sessions/[id]/auto-name/route";
import * as route31 from "../app/api/sessions/[id]/context/route";
import * as route32 from "../app/api/sessions/[id]/entries/[entryId]/thinking/route";
import * as route33 from "../app/api/sessions/[id]/entries/[entryId]/tool-result-image/route";
import * as route34 from "../app/api/sessions/[id]/export/route";
import * as route35 from "../app/api/sessions/[id]/route";
import * as route36 from "../app/api/sessions/[id]/state/route";
import * as route37 from "../app/api/sessions/route";
import * as route38 from "../app/api/sessions/search/route";
import * as route39 from "../app/api/skills/check/route";
import * as route40 from "../app/api/skills/install/route";
import * as route41 from "../app/api/skills/route";
import * as route42 from "../app/api/skills/search/route";
import * as route43 from "../app/api/skills/update/route";
import * as route44 from "../app/api/subagents/[id]/route";
import * as route45 from "../app/api/subagents/profiles/route";
import * as route46 from "../app/api/subagents/settings/route";
import * as route47 from "../app/api/terminal/[id]/events/route";
import * as route48 from "../app/api/terminal/[id]/route";
import * as route49 from "../app/api/terminal/route";
import * as route50 from "../app/api/tools/settings/route";
import * as route51 from "../app/api/web-auth/route";
import * as route52 from "../app/api/worktrees/route";

export const ROUTES: { path: string; module: RouteModule }[] = [
  { path: "/api/agent/[id]/bash-output", module: route0 as RouteModule },
  { path: "/api/agent/[id]/events", module: route1 as RouteModule },
  { path: "/api/agent/[id]/lease", module: route2 as RouteModule },
  { path: "/api/agent/[id]", module: route3 as RouteModule },
  { path: "/api/agent/new", module: route4 as RouteModule },
  { path: "/api/agent/running", module: route5 as RouteModule },
  { path: "/api/app-update", module: route6 as RouteModule },
  { path: "/api/auth/api-key/[provider]", module: route7 as RouteModule },
  { path: "/api/auth/login/[provider]", module: route8 as RouteModule },
  { path: "/api/auth/logout/[provider]", module: route9 as RouteModule },
  { path: "/api/auth/providers", module: route10 as RouteModule },
  { path: "/api/cwd/browse", module: route11 as RouteModule },
  { path: "/api/cwd/validate", module: route12 as RouteModule },
  { path: "/api/default-cwd", module: route13 as RouteModule },
  { path: "/api/file-index", module: route14 as RouteModule },
  { path: "/api/files/[...path]", module: route15 as RouteModule },
  { path: "/api/git/diff", module: route16 as RouteModule },
  { path: "/api/git/status", module: route17 as RouteModule },
  { path: "/api/home", module: route18 as RouteModule },
  { path: "/api/models-config/catalog", module: route19 as RouteModule },
  { path: "/api/models-config/discover", module: route20 as RouteModule },
  { path: "/api/models-config", module: route21 as RouteModule },
  { path: "/api/models-config/test", module: route22 as RouteModule },
  { path: "/api/models", module: route23 as RouteModule },
  { path: "/api/plugins/check", module: route24 as RouteModule },
  { path: "/api/plugins", module: route25 as RouteModule },
  { path: "/api/project-trust", module: route26 as RouteModule },
  { path: "/api/provider-usage/query", module: route27 as RouteModule },
  { path: "/api/push/config", module: route28 as RouteModule },
  { path: "/api/push/subscribe", module: route29 as RouteModule },
  { path: "/api/sessions/[id]/auto-name", module: route30 as RouteModule },
  { path: "/api/sessions/[id]/context", module: route31 as RouteModule },
  { path: "/api/sessions/[id]/entries/[entryId]/thinking", module: route32 as RouteModule },
  { path: "/api/sessions/[id]/entries/[entryId]/tool-result-image", module: route33 as RouteModule },
  { path: "/api/sessions/[id]/export", module: route34 as RouteModule },
  { path: "/api/sessions/[id]", module: route35 as RouteModule },
  { path: "/api/sessions/[id]/state", module: route36 as RouteModule },
  { path: "/api/sessions", module: route37 as RouteModule },
  { path: "/api/sessions/search", module: route38 as RouteModule },
  { path: "/api/skills/check", module: route39 as RouteModule },
  { path: "/api/skills/install", module: route40 as RouteModule },
  { path: "/api/skills", module: route41 as RouteModule },
  { path: "/api/skills/search", module: route42 as RouteModule },
  { path: "/api/skills/update", module: route43 as RouteModule },
  { path: "/api/subagents/[id]", module: route44 as RouteModule },
  { path: "/api/subagents/profiles", module: route45 as RouteModule },
  { path: "/api/subagents/settings", module: route46 as RouteModule },
  { path: "/api/terminal/[id]/events", module: route47 as RouteModule },
  { path: "/api/terminal/[id]", module: route48 as RouteModule },
  { path: "/api/terminal", module: route49 as RouteModule },
  { path: "/api/tools/settings", module: route50 as RouteModule },
  { path: "/api/web-auth", module: route51 as RouteModule },
  { path: "/api/worktrees", module: route52 as RouteModule },
];
