/**
 * Generates services/routes.gen.ts from the ported App Router tree.
 *
 * The web version relies on Next.js file-system routing. Outside Next.js the
 * routes still exist as plain modules, so we emit a static import table and
 * match paths ourselves in services/http-router.ts.
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const root = process.cwd();
const apiDir = join(root, "app", "api");
const outFile = join(root, "services", "routes.gen.ts");

/** @param {string} dir @param {string[]} acc */
function walk(dir, acc) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      walk(full, acc);
    } else if (entry === "route.ts") {
      acc.push(full);
    }
  }
  return acc;
}

const files = walk(apiDir, []).sort();

/** app/api/sessions/[id]/route.ts -> /api/sessions/[id] */
function toRoutePath(file) {
  const rel = relative(join(root, "app"), file).split(sep).join("/");
  return `/${rel.replace(/\/route\.ts$/, "")}`;
}

const lines = [
  "// GENERATED by scripts/gen-routes.mjs — do not edit by hand.",
  "/* eslint-disable */",
  'import type { RouteModule } from "./http-router";',
  "",
];

files.forEach((file, index) => {
  const spec = `../${relative(root, file).split(sep).join("/").replace(/\.ts$/, "")}`;
  lines.push(`import * as route${index} from "${spec}";`);
});

lines.push("", "export const ROUTES: { path: string; module: RouteModule }[] = [");
files.forEach((file, index) => {
  lines.push(`  { path: ${JSON.stringify(toRoutePath(file))}, module: route${index} as RouteModule },`);
});
lines.push("];", "");

writeFileSync(outFile, lines.join("\n"), "utf8");
console.log(`wrote ${relative(root, outFile)} (${files.length} routes)`);
