import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {fileURLToPath} from "node:url";
import test from "node:test";
import {build} from "esbuild";
const bundled=await build({entryPoints:[fileURLToPath(new URL('./backup-controller.ts',import.meta.url))],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent'});
const {BackupController}=await import('data:text/javascript;base64,'+Buffer.from(bundled.outputFiles[0].text).toString('base64'));
async function fixture(t){const home=await fs.mkdtemp(path.join(os.tmpdir(),"pi-backup-controller-"));t.after(()=>fs.rm(home,{recursive:true,force:true}));const agent=path.join(home,'agent'),target=path.join(home,'target'),userHome=path.join(home,'user');await Promise.all([agent,target,userHome].map(p=>fs.mkdir(p)));await fs.writeFile(path.join(agent,'auth.json'),'{"key":"SYNTHETIC"}');let current=agent,uiState={'pi-theme':'dark'},frozen=false,blocked=false;const events=[];const host={homeDir:userHome,appVersion:'test',applicationDir:path.join(home,'application'),pickProjects:async()=>[],pickMapping:async()=>target,pickArchive:async()=>path.join(home,'archive.pibak'),saveArchive:async()=>path.join(home,'archive.pibak'),info:async()=>({agentDir:current,cwd:home}),stopped:async work=>work(current,{resources:[],sessionDirs:[],warnings:[]}),ui:{read:async()=>({...uiState}),write:async s=>{uiState={...s};}},progress:(_owner,p)=>events.push(p),freezeUi:async v=>{frozen=v;},recoveryRequired:()=>{blocked=true;}};const controller=new BackupController(host);t.after(()=>controller.release(1));return{home,agent,target,controller,events,setTarget:()=>{current=target;uiState={'pi-theme':'light'};},state:()=>({uiState,frozen,blocked})};}
test('native selection token ownership, password confirmation and no-password inspection',async t=>{const f=await fixture(t);await fs.writeFile(path.join(f.home,'archive.pibak'),'selected-file');const selected=await f.controller.inspect(1,{kind:'select'});assert.ok(selected.token);await assert.rejects(f.controller.inspect(2,{kind:'unlock',token:selected.token,password:'test-password',operationId:'other'}),/expired/);await assert.rejects(f.controller.inspect(1,{kind:'unlock',token:selected.token,password:'',operationId:'empty'}),/password/);const scan=await f.controller.scan(1,{projectTokens:[],operationId:'scan',uiState:{}});await assert.rejects(f.controller.export(1,{token:scan.token,password:'test-password',confirmPassword:'wrong',operationId:'export',acknowledgeWarnings:true}),/match/);});
test('full controller flow freezes preferences, restores effective credentials and releases unlock key',async t=>{const f=await fixture(t);const scan=await f.controller.scan(1,{projectTokens:[],operationId:'scan',uiState:{'pi-theme':'dark'}});await f.controller.export(1,{token:scan.token,password:'test-password',confirmPassword:'test-password',operationId:'export',acknowledgeWarnings:true});f.setTarget();const selected=await f.controller.inspect(1,{kind:'select'});const unlocked=await f.controller.inspect(1,{kind:'unlock',token:selected.token,password:'test-password',operationId:'unlock'});const result=await f.controller.restore(1,{token:selected.token,decisions:unlocked.preview.resources.map(r=>({resourceId:r.id,conflict:'replace',activation:'enable'})),configurationConsent:true,operationId:'restore',planFingerprint:unlocked.preview.fingerprint});assert.equal(result.committed,true);assert.equal(JSON.parse(await fs.readFile(path.join(f.target,'auth.json'),'utf8')).key,'SYNTHETIC');assert.deepEqual(f.state(),{uiState:{'pi-theme':'dark'},frozen:false,blocked:false});await assert.rejects(f.controller.restore(1,{token:selected.token,decisions:[],configurationConsent:true,operationId:'again',planFingerprint:'stale'}),/expired/);assert.ok(f.events.some(p=>p.phase==='export'));});
test('cancel and navigation release selected archive tokens',async t=>{const f=await fixture(t);await fs.writeFile(path.join(f.home,'archive.pibak'),'selected-file');const s=await f.controller.inspect(1,{kind:'select'});await f.controller.cancel(1,{token:s.token});await assert.rejects(f.controller.inspect(1,{kind:'unlock',token:s.token,password:'pw',operationId:'expired'}),/expired/);const s2=await f.controller.inspect(1,{kind:'select'});f.controller.release(1);await assert.rejects(f.controller.inspect(1,{kind:'unlock',token:s2.token,password:'pw',operationId:'navigation'}),/expired/);});
